CREATE TABLE EventBody (
	"REQUEST_ID" NUMBER(38) NULL,
	"IDENTIFIER" VARCHAR2(50) NOT NULL,
	"ACTIONCODE" VARCHAR2(250) NOT NULL,
	"CREATEDAT" TIMESTAMP NOT NULL,
	"BUSINESSENTITY" VARCHAR2(25) NULL,
	"BUSINESSENTITYREF" VARCHAR2(60) NULL,
	"EXTENSIONTEXT" VARCHAR2(2000) NULL,
	"SESSIONID" VARCHAR2(60) NOT NULL,
	"EVENTCHANNEL" VARCHAR2(60) NOT NULL,
	"LASTPROCESSLOG_ID" NUMBER(38) NULL,
	"EVENTBODY_ID" NUMBER(38) NOT NULL
);
ALTER TABLE EventBody ADD PRIMARY KEY (EventBody_ID);

CREATE TABLE ActiveEvent (
	"EVENTBODY_ID" NUMBER(38) NOT NULL,
	"NEXTPROCESSTIME" TIMESTAMP NOT NULL,
	"APPLICATIONRUNTIME_ID" NUMBER(38) NULL,
	"EVENTCHANNEL" VARCHAR2(60) NOT NULL,
	"STATE" CHAR(1) NOT NULL,
	"ACTIVEEVENT_ID" NUMBER(38) NOT NULL
);
ALTER TABLE ActiveEvent ADD PRIMARY KEY (ActiveEvent_ID);

CREATE TABLE EventBinaryContent (
	"LOBDATA" BLOB NOT NULL,
	"MIMETYPE" VARCHAR2(25) NOT NULL,
	"EVENTBINARYCONTENT_ID" NUMBER(38) NOT NULL
);
ALTER TABLE EventBinaryContent ADD PRIMARY KEY (EventBinaryContent_ID);

CREATE TABLE EventProcessLog (
	"EVENTBODY_ID" NUMBER(38) NOT NULL,
	"RESULTCODE" VARCHAR2(250) NULL,
	"PROCESSSTARTTIME" TIMESTAMP NULL,
	"PROCESSFINISHTIME" TIMESTAMP NULL,
	"RESULT_ID" NUMBER(38) NULL,
	"APPLICATIONRUNTIME_ID" NUMBER(38) NOT NULL,
	"STATE" CHAR(1) NOT NULL,
	"ORDERNO" NUMBER(18) NOT NULL,
	"ALLOCATIONTIME" TIMESTAMP NOT NULL,
	"EXPECTEDALLOCATIONTIME" TIMESTAMP NOT NULL,
	"EVENTPROCESSLOG_ID" NUMBER(38) NOT NULL
);
ALTER TABLE EventProcessLog ADD PRIMARY KEY (EventProcessLog_ID);

CREATE TABLE ApplicationRuntime (
	"STARTTIME" TIMESTAMP NOT NULL,
	"STOPTIME" TIMESTAMP NULL,
	"LASTTOUCHTIME" TIMESTAMP NOT NULL,
	"CODE" VARCHAR2(25) NOT NULL,
	"APPLICATIONRUNTIME_ID" NUMBER(38) NOT NULL
);
ALTER TABLE ApplicationRuntime ADD PRIMARY KEY (ApplicationRuntime_ID);

CREATE TABLE EventChannel (
	"CODE" VARCHAR2(60) NOT NULL,
	"EVENTCHANNEL_ID" NUMBER(38) NOT NULL
);
ALTER TABLE EventChannel ADD PRIMARY KEY (EventChannel_ID);

