
logging:
  level:
    ROOT: INFO
    org.smartbit4all.businessevent: DEBUG

spring:
  profiles:
    active: mock
  devtools:
    restart:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  datasource:
#    url: jdbc:h2:file:./build/h2db/db/nova-border-eu-stat;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver    
    username: sa
    password:
#    sqlScriptEncoding: UTF-8
#    schema: classpath:/mock/schema-mock.sql
#    data: classpath*:/mock/data-mock.sql
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: none
