
CREATE INDEX EventBody_REQUEST_ID_IDX ON EventBody (REQUEST_ID);

CREATE INDEX EventBody_LASTPROCESSLOG_ID_IDX ON EventBody (LASTPROCESSLOG_ID);


CREATE INDEX ActiveEvent_EVENTBODY_ID_IDX ON ActiveEvent (EVENTBODY_ID);

CREATE INDEX ActiveEvent_APPLICATIONRUNTIME_ID_IDX ON ActiveEvent (APPLICATIONRUNTIME_ID);





CREATE INDEX EventProcessLog_EVENTBODY_ID_IDX ON EventProcessLog (EVENTBODY_ID);

CREATE INDEX EventProcessLog_RESULT_ID_IDX ON EventProcessLog (RESULT_ID);

CREATE INDEX EventProcessLog_APPLICATIONRUNTIME_ID_IDX ON EventProcessLog (APPLICATIONRUNTIME_ID);




CREATE UNIQUE INDEX EventChannel_CHIDENTIFIER_IDX ON EventChannel (code);

