swagger: "2.0"
info:
  description: "This is the Business Event API."
  version: "1.0.0"
  title: "Business Event Module"
  termsOfService: ""
  contact:
    email: "platform@it4all.hu"
host: "localhost:8090"
basePath: "/v1"
tags:
- name: "businessevent"
  description: "Business Event Module"  
schemes:
- "http"
- "https"
paths:
  /postEvent:
    post:
      tags:
        - "businessevent"
      summary: "Post an event to the event module."
      operationId: "postEvent"
      consumes:
       - "application/json"
      produces:
       - "application/json"
      parameters:
       - in: "body"
         name: "body"
         description: "The event to start processing"
         required: true
         schema:
           $ref: "#/definitions/BusinessEventRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: '#/definitions/BusinessEventState'
  /checkEvent:
    post:
      tags:
        - "businessevent"
      summary: "Check a given event and take the result if it has any."
      operationId: "checkEvent"
      consumes:
       - "application/json"
      produces:
       - "application/json"
      parameters:
       - in: "body"
         name: "body"
         description: "The start request for the process"
         required: true
         schema:
           $ref: '#/definitions/BusinessEventRequest'
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: '#/definitions/BusinessEventState'
definitions:
  BusinessEventRequest:
    type: "object"
    required:
    - "channel"
    - "actionCode"
    properties:
      channel:
        type: "string"
      sessionId:
        type: "string"
      actionCode:
        description: "The qualified name of the function to execute"
        type: "string"
      businessEntity:
        description: "The name of the entity the function execution is related with."
        type: "string"
      businessEntityRef:
        description: "The identifier of the related entity. Parameter of the function."
        type: "string"
      extensionText:
        description: "A free for parameter for function."
        type: "string"
      nextProcessTime:
        description: "The next process time in case a scheduled channel."
        type: string
        format: date-time

  BusinessEventState:
    type: "object"
    required:
    - "eventId"
    - "channel"
    - "numberOfProcessing"
    - "state"
    properties:
      eventId:
        type: "integer"
        format: "int64"
      channel:
        type: "string"
      sessionId:
        type: "string"
      numberOfProcessing:
        type: "integer"
        format: "int64"
      state:
        type: "string"
        enum:
        - "NEW"
        - "PROCESSING"
        - "WAITING"
        - "PROCESSED"
